### ISSUE TITLE
oroconf extract defunct 

### ISSUE THREAD

**Issue by planthaber** [rock-core/tools-orocosrb#51] opened 2015-04-20 11:56 UTC
When trying to call oroconf extract from a bundle, i get this error message:

> configurations.rb:676:in `save': undefined method `in_context' for Orocos::TaskConfigurations:Class

Full log:

>Bundles[INFO]: Active bundles: entern, rock
Generating task Spaceclimber from file /home/planthaber/dfki/rock/entern/install/configuration/spaceclimber_monster/FramesCombined.xml
orocos.rb[WARN]: killing running task contexts and deployments because of unhandled exception
orocos.rb[WARN]:   /home/planthaber/dfki/rock/entern/tools/orocos.rb/lib/orocos/configurations.rb:676:in `save': undefined method `in_context' for Orocos::TaskConfigurations:Class
orocos.rb[WARN]:     /home/planthaber/dfki/rock/entern/tools/orocos.rb/bin/oroconf:87:in `dump_configuration'
orocos.rb[WARN]:     /home/planthaber/dfki/rock/entern/tools/orocos.rb/bin/oroconf:106:in `block in <main>'
orocos.rb[WARN]:     /home/planthaber/dfki/rock/entern/tools/orocos.rb/lib/orocos/process.rb:695:in `block in run'
orocos.rb[WARN]:     /home/planthaber/dfki/rock/entern/tools/orocos.rb/lib/orocos/process.rb:1098:in `guard'
orocos.rb[WARN]:     /home/planthaber/dfki/rock/entern/tools/orocos.rb/lib/orocos/process.rb:694:in `run'
orocos.rb[WARN]:     /home/planthaber/dfki/rock/entern/tools/orocos.rb/lib/orocos/process.rb:107:in `run'
orocos.rb[WARN]:     /home/planthaber/dfki/rock/entern/tools/orocos.rb/bin/oroconf:104:in `<main>'

**Comment by saarnold** [comment] 2015-04-20 18:04
This was introduced with this commit 01f78bb0a2c0f59f262b73f60f6934a184122830
The problem is that the instance method in_context is called by the class method save.

**Comment by doudou** [comment] 2015-04-23 19:27
This should be fixed by #52. Could you check that ?

**Closed** 2015-04-24 13:34 UTC
